// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlsdkcyjqzvzacjgfksv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsc2RrY3lqcXp2emFjamdma3N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTM3NjksImV4cCI6MjA2MzcyOTc2OX0.IIbi5HFn1L4Dbsd8Ns_1qvDb1CpuNFBTUUuGvpiX6ss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);